import { readFileSync, writeFileSync } from 'node:fs'
import { expect, test } from 'vitest'
import { tradition } from '@/lib/tradition/registry'
import { silhouette } from '@/lib/core/silhouette'

/**
 * The first house's computed silhouette, as a file.
 *
 * It was the favicon until the collection got a mark of its own — a tab icon
 * of one house was a reasonable thing for a site about one house, and became
 * a claim about the other thirty-four. The drawing is still an output of the
 * generator like every other picture here, and like every other output it can
 * drift when the model changes, so it is still held against the generator.
 *
 * To regenerate after a deliberate model change:
 *   WRITE_ICON=1 pnpm vitest run test/icon.test.ts
 */
function iconSvg(): string {
  const t = tradition('toraja')
  const b = t.build(t.defaultQuery)
  const s = silhouette(b.house, b.scene.ridgeAxis ?? 0)
  const w = s.max[0] - s.min[0]
  const h = s.max[1]
  // A square frame around the house, sized by its wider extent.
  const side = Math.max(w, h) * 1.14
  const ox = (side - w) / 2
  const oy = (side - h) / 2
  const f = (n: number) => (Math.round(n * 100) / 100).toString()
  const d = s.loops
    .map(
      (loop) =>
        'M' +
        loop.map(([x, y]) => `${f(ox + x - s.min[0])} ${f(side - oy - y)}`).join('L') +
        'Z',
    )
    .join('')
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${f(side)} ${f(side)}">`,
    `<!-- The tongkonan's elevation silhouette, generated by lib/core/silhouette.ts`,
    `     from the default rule pack. Regenerate with test/ if the model changes. -->`,
    `<rect width="${f(side)}" height="${f(side)}" rx="${f(side * 0.08)}" fill="#D8D7CD"/>`,
    `<path d="${d}" fill="#17150F" fill-rule="evenodd"/>`,
    `</svg>`,
  ].join('\n')
}

test('the committed silhouette is what the generator draws', () => {
  const svg = iconSvg()
  if (process.env.WRITE_ICON) writeFileSync('public/tongkonan.svg', svg)
  expect(readFileSync('public/tongkonan.svg', 'utf8')).toBe(svg)
})
